# Generated by Django 5.1.1 on 2024-11-06 04:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(default='', max_length=100)),
                ('handshape', models.CharField(default='1', max_length=100)),
                ('location', models.CharField(default='Forehead', max_length=100)),
                ('movement', models.CharField(default='Elbow Out', max_length=100)),
                ('video', models.FileField(null=True, upload_to='sign_videos')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
