# Generated by Django 5.1.1 on 2024-10-02 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Demonstration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Sign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sign_name', models.CharField(default='', max_length=100)),
                ('handshape', models.CharField(choices=[('1', '1'), ('3', '3')], default='1', max_length=100)),
                ('location', models.CharField(choices=[('Bent', 'Bent'), ('Crossed', 'Crossed')], default='Bent', max_length=100)),
                ('movement', models.CharField(choices=[('Asymmetrical Different Handshape', 'Asymmetrical Different Handshape'), ('Asymmetrical Same Handshape', 'Asymmetrical Same Handshape')], default='Asymmetrical Different Handshape', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
