# Generated by Django 5.1.1 on 2024-10-02 13:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('signs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='demonstration',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='set',
            name='contained_signs',
            field=models.ManyToManyField(related_name='signs', to='signs.sign'),
        ),
        migrations.AddField(
            model_name='demonstration',
            name='sign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signs.sign'),
        ),
    ]
