# Generated by Django 5.1.1 on 2024-10-23 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sign',
            name='handshape',
            field=models.CharField(default='1', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='location',
            field=models.CharField(default='Forehead', max_length=100),
        ),
        migrations.AlterField(
            model_name='sign',
            name='movement',
            field=models.CharField(default='Elbow Out', max_length=100),
        ),
    ]
