# Generated by Django 5.1.1 on 2024-11-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signs', '0004_sign_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='sign',
            name='video',
            field=models.FileField(null=True, upload_to='sign_videos'),
        ),
    ]
