"""
This module defines the URL patterns for the 'signs' application.
Imports:
    - path, include: Functions from django.urls to define URL patterns.
    - routers: DefaultRouter from rest_framework to create a router for the API.
    - SignViewSet: ViewSet from the local api module to handle sign-related API requests.
    - views: Local module to handle non-API views.
Router:
    - A DefaultRouter instance is created and the SignViewSet is registered with the route 'api/signs'.
URL Patterns:
    - The urlpatterns list is set to the URLs generated by the router.
"""
from django.urls import path, include
from rest_framework import routers
from .api import SignViewSet

from . import views
# Create your views here.
router = routers.DefaultRouter()
router.register("api/signs", SignViewSet, "signs")

#urlpatterns = [
    #path("", views.SignFilterView.as_view(), name = "user-filter" )
#]
urlpatterns = router.urls
