"""
This module defines the URL patterns for the 'signs' application.
Imports:
    - path, include: Functions from django.urls to define URL patterns.
    - routers: DefaultRouter from rest_framework to create a router for the API.
    - SignViewSet: ViewSet from the local api module to handle sign-related API requests.
    - views: Local module to handle non-API views.
Router:
    - A DefaultRouter instance is created and the SignViewSet is registered with the route 'api/signs'.
URL Patterns:
    - The urlpatterns list is set to the URLs generated by the router.
"""
from django.urls import path, include
from rest_framework import routers
from .api import SignViewSet, SignNameViewSet, LoginView, RegisterView, get_csrf

from . import views
# Create your views here.
router = routers.DefaultRouter()
router.register("api/signs", SignViewSet, "signs")
router.register("api/sign", SignNameViewSet, "sign_name")
#router.register("api/login", LoginView, "api-login")

#urlpatterns = [
    #path("", views.SignFilterView.as_view(), name = "user-filter" )
#]
urlpatterns = router.urls
urlpatterns.append(path("api/login/", LoginView, name="loginView"))
urlpatterns.append(path("api/register/", RegisterView, name="registerView"))
urlpatterns.append(path("api/get_csrf/", get_csrf, name="get_csrf"))
